services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"

  worker1:
    build: ./Backend
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker2:
    build: ./Backend
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker3:
    build: ./Backend
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: ./my-app
    ports:
      - "3000:3000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
