version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000                # ✅ Fix: Explicit backend port
    depends_on:
      - redis
    networks:
      - app-network

  worker1:
    build: ./Backend
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  worker2:
    build: ./Backend
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  worker3:
    build: ./Backend
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
